#ifndef C_COMPILER_TOKEN_H
#define C_COMPILER_TOKEN_H

#include <string>
#include <vector>
#include <set>
#include "preprocessor.h"

enum class TokenKind {
    // Keywords
    KW_AUTO, KW_BREAK, KW_CASE, KW_CHAR, KW_CONST, KW_CONTINUE, KW_DEFAULT,
    KW_DO, KW_DOUBLE, KW_ELSE, KW_ENUM, KW_EXTERN, KW_FLOAT, KW_FOR, KW_GOTO,
    KW_IF, KW_INLINE, KW_INT, KW_LONG, KW_REGISTER, KW_RESTRICT, KW_RETURN,
    KW_SHORT, KW_SIGNED, KW_SIZEOF, KW_STATIC, KW_STRUCT, KW_SWITCH,
    KW_TYPEDEF, KW_UNION, KW_UNSIGNED, KW_VOID, KW_VOLATILE, KW_WHILE,
    KW__ALIGNAS, KW__ALIGNOF, KW__ATOMIC, KW__BOOL, KW__COMPLEX,
    KW__GENERIC, KW__IMAGINARY, KW__NORETURN, KW__STATIC_ASSERT,
    KW__THREAD_LOCAL,
    // C23
    KW_CONSTEXPR, KW_TYPEOF, KW_TYPEOF_UNQUAL, KW_NULLPTR, KW_TRUE, KW_FALSE,
    KW_STATIC_ASSERT,
    // C++ keywords
    KW_ALIGNAS, KW_ALIGNOF, KW_CLASS, KW_NAMESPACE, KW_TEMPLATE, KW_TYPENAME,
    KW_PUBLIC, KW_PRIVATE, KW_PROTECTED, KW_VIRTUAL, KW_OVERRIDE, KW_FINAL,
    KW_EXPLICIT, KW_MUTABLE, KW_FRIEND, KW_OPERATOR, KW_THIS, KW_NEW, KW_DELETE,
    KW_THROW, KW_TRY, KW_CATCH, KW_NOEXCEPT, KW_DECLTYPE, KW_STATIC_CAST,
    KW_DYNAMIC_CAST, KW_CONST_CAST, KW_REINTERPRET_CAST,
    KW_CHAR16_T, KW_CHAR32_T, KW_CHAR8_T,
    KW_CONSTEVAL, KW_CONSTINIT,
    KW_CO_AWAIT, KW_CO_YIELD, KW_CO_RETURN,
    KW_CONCEPT, KW_REQUIRES, KW_EXPORT, KW_IMPORT, KW_MODULE,

    // Punctuators / Operators
    PLUS, MINUS, STAR, DIVIDE, MOD,
    PLUSPLUS, MINUSMINUS,
    EQ, NE, LT, GT, LE, GE, SPACESHIP,
    AND, OR, NOT,
    AMPER, PIPE, CARET, DOUBLE_CARET, TILDE,
    LSHIFT, RSHIFT,
    ASSIGN, ADD_ASSIGN, SUB_ASSIGN, MUL_ASSIGN, DIV_ASSIGN, MOD_ASSIGN,
    AND_ASSIGN, OR_ASSIGN, XOR_ASSIGN, LSHIFT_ASSIGN, RSHIFT_ASSIGN,
    DOT, ARROW, DOT_STAR, ARROW_STAR, SCOPE,
    LPAREN, RPAREN, LBRACKET, RBRACKET, LBRACE, RBRACE,
    SEMICOLON, COLON, COMMA, QUESTION, ELLIPSIS,
    HASH, HASHHASH,

    // Literals / Identifiers
    IDENTIFIER, TYPE_NAME, NUMBER, STRING_LITERAL, CHAR_LITERAL,

    // Special
    END_OF_FILE, ERROR
};

struct ParserToken {
    TokenKind kind;
    std::string value;
    std::string filename;
    int line;
    int column;
};

std::vector<ParserToken> refine_tokens(const std::vector<Token>& pp_tokens, std::set<std::string>& typedef_names);

#endif
